### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by chammiii** [anurag2947/GoIndex-Downloader#1]
Not working now
Given following error
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-bed896f2216e> in <module>()
    139 
    140 domain = URL.split(".dev")[0] + ".dev" #get domain name from URL
--> 141 getLinks(URL, path)
    142 driver.quit()
    143 print("\n::Link Fetch and Folders Creation Complete::")

<ipython-input-5-bed896f2216e> in getLinks(pageUrl, path)
     31 
     32     page_source = BeautifulSoup(html, 'lxml')
---> 33     tags_a_list = page_source.find('ul').find_all_next('a')
     34 
     35 

AttributeError: 'NoneType' object has no attribute 'find_all_next'

**Comment by anurag2947** [comment]
Can you check if the issue is solved?
If not then share the link you are trying to download.
